# Generated by Django 3.0.7 on 2020-07-27 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_pic', models.ImageField(default='Bloggers/profile.png', upload_to='Bloggers')),
                ('bio', models.TextField()),
                ('locality', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=25)),
                ('country', models.CharField(max_length=25)),
                ('instagram', models.URLField(blank=True, null=True, unique=True)),
                ('linkedin', models.URLField(blank=True, null=True, unique=True)),
                ('facebook', models.URLField(blank=True, null=True, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogType', models.CharField(choices=[('Sneak Peek', 'Sneak Peek'), ('Events', 'Events'), ('Lifestyle', 'Lifestyle'), ('Trends', 'Trends')], max_length=25, null=True)),
                ('title', models.CharField(max_length=25)),
                ('cover', models.ImageField(upload_to='Blog Image')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('approve', models.BooleanField(default=False)),
                ('recommend', models.BooleanField(default=False)),
                ('time', models.IntegerField()),
                ('post_writer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', related_query_name='tag', to='Blog.Writer')),
            ],
        ),
    ]
