# Generated by Django 3.0.7 on 2020-07-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regType', models.CharField(choices=[('Sneek Peek', 'Self'), ('Events', 'Events'), ('Lifestyle', 'Lifestyle'), ('Trends', 'Trends')], max_length=25, null=True)),
                ('title', models.CharField(max_length=25)),
                ('cover', models.ImageField(upload_to='Blog Image')),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=25)),
                ('timestamp', models.DateTimeField(blank=True)),
                ('approve', models.BooleanField(default=False)),
                ('recommend', models.BooleanField(default=False)),
                ('time', models.IntegerField()),
            ],
        ),
    ]
