# Generated by Django 3.0.7 on 2020-07-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200722_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='regType',
        ),
        migrations.AddField(
            model_name='post',
            name='blogType',
            field=models.CharField(choices=[('Sneek Peek', 'Sneek Peek'), ('Events', 'Events'), ('Lifestyle', 'Lifestyle'), ('Trends', 'Trends')], max_length=25, null=True),
        ),
    ]
