# Generated by Django 3.0.7 on 2020-07-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20200727_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
