# Generated by Django 3.0.7 on 2020-07-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
