# Generated by Django 3.0.7 on 2020-07-22 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0004_auto_20200722_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('username', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_pic', models.ImageField(upload_to='Bloggers')),
                ('bio', models.TextField()),
                ('locality', models.TextField()),
                ('state', models.TextField()),
                ('country', models.TextField()),
                ('instagram', models.URLField(null=True, unique=True)),
                ('linkedin', models.URLField(null=True, unique=True)),
                ('facebook', models.URLField(null=True, unique=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Writer'),
        ),
    ]
