# Generated by Django 3.0.7 on 2020-07-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20200724_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='name',
        ),
        migrations.AddField(
            model_name='writer',
            name='author',
            field=models.CharField(default=1, max_length=25),
            preserve_default=False,
        ),
    ]
