# Generated by Django 3.0.7 on 2020-07-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20200724_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='writer',
            name='author',
        ),
    ]
