# Generated by Django 3.0.7 on 2020-07-24 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_auto_20200724_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='username',
        ),
    ]
