# Generated by Django 3.0.7 on 2020-08-01 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0010_auto_20200802_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.ManyToManyField(blank=True, related_name='blog_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
