# Generated by Django 3.0.8 on 2020-07-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0010_remove_writer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
