# Generated by Django 3.0.7 on 2020-08-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_auto_20200802_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='blogType',
            field=models.CharField(choices=[('Sneak Peek', 'Sneak Peek'), ('Events', 'Events'), ('Lifestyle', 'Lifestyle'), ('Trends', 'Trends'), ('Science & Technology', 'Science & Technology')], max_length=25, null=True),
        ),
    ]
