# Generated by Django 3.0.8 on 2020-07-25 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0012_post_post_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
