# Generated by Django 3.0.8 on 2020-08-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_auto_20200809_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='declined',
            field=models.BooleanField(default=False),
        ),
    ]
