# Generated by Django 3.0.8 on 2020-07-25 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0014_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
