# Generated by Django 3.0.7 on 2020-11-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0015_writer_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='fullname',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
