# Generated by Django 3.0.7 on 2020-07-20 07:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
