# Generated by Django 3.0.7 on 2020-07-30 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_blogcomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='parent',
        ),
    ]
