# Generated by Django 3.0.7 on 2020-11-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_remove_blogcomment_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30, null=True)),
                ('photo', models.ImageField(upload_to='Ads')),
                ('tagline', models.TextField(null=True)),
            ],
        ),
    ]
